import streamlit as st
import json
import os

st.title('💡 Lead Scoring Demo')
st.markdown('''
This is a minimal Streamlit app that demonstrates the lead scoring skill.
It loads the JSON file generated by the Flask‑based backend (if present) and
shows a table with the scored leads.
''')

json_path = os.path.join(os.path.dirname(__file__), 'scored_leads.json')
if os.path.exists(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    st.subheader('Scored Leads')
    st.dataframe(data)
else:
    st.info('No scored leads found yet. Run the Flask app or upload `scored_leads.json` first.')
